### get all articles
GET http://localhost:8080/articles
Content-Type: application/json
Accept: application/json

### get article by id
GET http://localhost:8080/articles/1
Content-Type: application/json
Accept: application/json

### save an article
POST http://localhost:8080/articles
Content-Type: application/json
Accept: application/json

{
  "title": "Article title 1",
  "text": "Article text and bla ble",
  "publicationDate": "2022-02-02"
}